name: Flutter CI (Prominder APK Build)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/prominder-${VERSION}-build-${{ github.run_number }}.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: prominder-apk
          path: build/app/outputs/flutter-apk/prominder-*.apk
          retention-days: 7
